// Generated by supabase gen types kotlin
// Run: supabase gen types kotlin --project-id YOUR_PROJECT_ID > app/common/src/main/kotlin/com/ticket/common/supabase/SupabaseTypes.kt

import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.Serializable

// Ticket types
@Serializable
data class TicketDB(
    val id: String,
    val title: String,
    val description: String?,
    val status: String,
    val priority: String,
    val category: String?,
    val created_by: String,
    val created_at: Float8,
    val updated_at: Float8,
    val assigned_to: String?
)

// Comment types
@Serializable
data class CommentDB(
    val id: String,
    val ticket_id: String,
    val text: String,
    val author: String,
    val created_at: Float8
)

// User types  
@Serializable
data class UserDB(
    val id: String,
    val email: String,
    val app_meta_data: Map<String, Any>,
    val user_meta_data: Map<String, Any>,
    val aud: String,
    val role: String,
    val last_sign_in_at: Float8,
    val updated_at: Float8,
    val phone: String?
)

// Storage types
@Serializable
data class FilePath(
    val bucketId: String,
    val filePath: String,
    val outermostPath: String
)

object Tables {
    object Ticket extends Table("tickets") {
        val id = column(id)
        val title = column(title)
        val description = column(description)
        val status = column(status)
        val priority = column(priority)
        val category = column(category)
        val createdBy = column(created_by)
        val createdAt = column(created_at)
        val updatedAt = column(updated_at)
        val assignedTo = column(assigned_to)
    }
    
    object Comment extends Table("comments") {
        val id = column(id)
        val ticketId = column(ticket_id)
        val text = column(text)
        val author = column(author)
        val createdAt = column(created_at)
    }
    
    object Users extends Table("users") {
        val id = column(id)
        val email = column(email)
        val role = column(role)
        val createdAt = column(created_at)
    }
}